### PR TITLE
Update docker-compose.yml

### PR DESCRIPTION
**Pull request by rishavanand**
Typo: prevented volume from being mounted

### CODE REVIEW

**Comment by d4rkstar** [comment]
Thank you!

**Comment by d4rkstar** [comment]
Thankyou!

**Comment by Saikishorkhadge** [comment]
kong unable to connect to konga

**Comment by d4rkstar** [comment]
> kong unable to connect to konga

Please open a new issue: if you can, add also details like log or other useful informations.

Regards

**Pull request merged**
